"""Convert evaluation JSON results to LaTeX table rows for paper/main.tex.

Reads JSON outputs from evaluate_checkpoint.py and compute_baselines.py,
generates formatted LaTeX rows ready to paste.

Usage:
    # Generate all table rows from evaluation results
    python scripts/json_to_latex.py \
        --eval_results eval_results.json \
        --baselines results/baselines.json \
        --output paper/generated_tables.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

PROCEDURES = [
    "rhinoplasty",
    "blepharoplasty",
    "rhytidectomy",
    "orthognathic",
    "brow_lift",
    "mentoplasty",
]
PROCEDURE_NAMES = {
    "rhinoplasty": "Rhinoplasty",
    "blepharoplasty": "Blepharoplasty",
    "rhytidectomy": "Rhytidectomy",
    "orthognathic": "Orthognathic",
    "brow_lift": "Brow Lift",
    "mentoplasty": "Mentoplasty",
}
FITZ_TYPES = ["I", "II", "III", "IV", "V", "VI"]


def fmt(val: float | None, decimals: int = 4) -> str:
    """Format a float for LaTeX, or -- if None/0."""
    if val is None or val == 0.0:
        return "--"
    return f"{val:.{decimals}f}"


def generate_results_table(
    baselines: dict | None = None,
    eval_results: dict | None = None,
) -> str:
    """Generate Table 1 (main results) LaTeX rows."""
    lines = []

    for proc in PROCEDURES:
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{6}}{{c}}{{\\textit{{{PROCEDURE_NAMES[proc]}}}}} \\\\")
        lines.append("\\midrule")

        # Baseline rows
        if baselines:
            for method_key, method_name in [("tps", "TPS-only"), ("morphing", "Morphing")]:
                m = baselines.get("methods", {}).get(method_key, {})
                pp = m.get("per_procedure", {}).get(proc, m.get("metrics", {}))
                fid = fmt(pp.get("fid"), 1)
                lpips = fmt(pp.get("lpips"))
                nme = fmt(pp.get("nme"))
                ssim = fmt(pp.get("ssim"))
                arcface = fmt(pp.get("identity_sim"))
                lines.append(
                    f"{method_name:20s} & {fid:>6s} & {lpips:>6s} & "
                    f"{nme:>6s} & {ssim:>6s} & {arcface:>6s} \\\\"
                )

        # Placeholder baselines we don't compute
        lines.append(
            f"{'SD1.5 Img2Img':20s} & {'--':>6s} & {'--':>6s} & "
            f"{'--':>6s} & {'--':>6s} & {'--':>6s} \\\\"
        )
        lines.append(
            f"{'Pix2Pix':20s} & {'--':>6s} & {'--':>6s} & {'--':>6s} & {'--':>6s} & {'--':>6s} \\\\"
        )

        # Our method
        if eval_results:
            pp = eval_results.get("per_procedure", {}).get(proc, eval_results.get("metrics", {}))
            fid = fmt(pp.get("fid"), 1)
            lpips = fmt(pp.get("lpips"))
            nme = fmt(pp.get("nme"))
            ssim = fmt(pp.get("ssim"))
            arcface = fmt(pp.get("identity_sim"))
            lines.append(
                f"\\textbf{{\\method{{}}}} & \\textbf{{{fid}}} & \\textbf{{{lpips}}} & "
                f"\\textbf{{{nme}}} & \\textbf{{{ssim}}} & \\textbf{{{arcface}}} \\\\"
            )
        else:
            lines.append("\\textbf{\\method{}} & -- & -- & -- & -- & -- \\\\")

    return "\n".join(lines)


def generate_fitzpatrick_table(
    eval_results: dict | None = None,
    baselines: dict | None = None,
) -> str:
    """Generate Table 3 (Fitzpatrick) LaTeX rows."""
    lines = []

    # Use eval results if available, otherwise baselines
    source = eval_results or {}
    fitz_data = source.get("per_fitzpatrick", {})

    for metric, label, decimals in [
        ("nme", "NME $\\downarrow$", 4),
        ("lpips", "LPIPS $\\downarrow$", 4),
        ("ssim", "SSIM $\\uparrow$", 4),
        ("identity_sim", "ArcFace $\\uparrow$", 4),
    ]:
        vals = []
        for ft in FITZ_TYPES:
            v = fitz_data.get(ft, {}).get(metric)
            vals.append(fmt(v, decimals))
        lines.append(f"{label:25s} & {' & '.join(vals)} \\\\")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert JSON results to LaTeX")
    parser.add_argument(
        "--eval_results", default=None, help="Path to evaluate_checkpoint.py JSON output"
    )
    parser.add_argument(
        "--baselines", default=None, help="Path to compute_baselines.py JSON output"
    )
    parser.add_argument("--output", default=None, help="Output .tex file (or stdout)")
    args = parser.parse_args()

    eval_results = None
    baselines = None

    if args.eval_results and Path(args.eval_results).exists():
        with open(args.eval_results) as f:
            eval_results = json.load(f)

    if args.baselines and Path(args.baselines).exists():
        with open(args.baselines) as f:
            baselines = json.load(f)

    output = []
    output.append("% Auto-generated by scripts/json_to_latex.py")
    output.append("% Do not edit manually — regenerate from JSON results")
    output.append("")

    output.append("% === Table 1: Main Results ===")
    output.append(generate_results_table(baselines, eval_results))
    output.append("")

    output.append("% === Table 3: Fitzpatrick Stratification ===")
    output.append(generate_fitzpatrick_table(eval_results, baselines))

    text = "\n".join(output)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w") as f:
            f.write(text)
        print(f"LaTeX tables saved to {args.output}")
    else:
        print(text)


if __name__ == "__main__":
    main()
